#!/bin/sh
# Build every artifact a release needs, in one command.
#
#   ./scripts/build-release.sh              store-safe (mirrors stripped)
#   ./scripts/build-release.sh --mirrors    full build, mirrors included
#
# Produces, in dist-store/:
#   corpus-retriever-<version>[-mirrors].zip                Chrome Web Store
#   corpus-retriever-<version>-firefox[-mirrors].xpi        Firefox (AMO)
#   corpus-retriever-<version>-SOURCE.zip                   AMO reviewers
#
# ONE script rather than two, because the two targets are not independent: both are packaged
# from the SAME generated files, and those generators are order-dependent. Building Chrome and
# then Firefox by hand meant running four steps twice and trusting that nothing had changed in
# between -- and the failure is silent, since a package built from a stale bundle looks
# perfectly normal and simply behaves like an older version.
#
# The AMO source archive is here for the same reason. It was previously produced by hand and
# was therefore missing from a release, which stalls review: AMO requires it whenever the
# submitted package contains generated code, and this one is generated by definition.

set -e

cd "$(dirname "$0")/.."

MIRRORS=""
SUFFIX=""
for arg in "$@"; do
  case "$arg" in
    --mirrors|--with-mirrors) MIRRORS="--with-mirrors"; SUFFIX="-mirrors" ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

VERSION=$(node -p "require('./extension/manifest.json').version")

echo "==> corpus-retriever $VERSION $([ -n "$MIRRORS" ] && echo '(with mirrors)' || echo '(store-safe)')"
echo "==> node $(node -v), npm $(npm -v)"

# 1. Dependencies. All are devDependencies used at BUILD time; none ship in the package.
echo "==> npm ci"
npm ci

# 2. Vendor the qpdf WebAssembly build.
#
# Copies extension/vendor/qpdf.{js,wasm} out of node_modules/@neslinesli93/qpdf-wasm. THIRD
# PARTY, Apache-2.0, vendored byte-for-byte unmodified -- it is not compiled here. It arrives
# minified from upstream; that is the one machine-generated artifact in the package.
echo "==> vendor qpdf"
npm run vendor:qpdf

# 3 and 4 are ORDER-DEPENDENT and each reads what the previous one wrote: the publisher
# bundle feeds the inliner, and the inliner feeds both packagers. Running them out of order
# silently produces a package built from stale generated code.
echo "==> bundle publishers"
node scripts/bundle-publishers.mjs

echo "==> inline modules into background.js"
node scripts/inline-search-sources.mjs

# 5. The gate. A package that fails its own tests must not reach a store, and finding that
# out after upload costs a review cycle.
echo "==> check + test"
npm run check
npm test

# 6. Both packages, from the one set of generated files.
echo "==> package (chrome)"
node scripts/build-store-package.mjs $MIRRORS

echo "==> package (firefox)"
node scripts/build-store-package.mjs --firefox $MIRRORS

# 7. The source archive AMO reviewers get.
#
# git archive, not a zip of the working tree: it emits exactly what is committed, so the
# reviewer's copy cannot contain a stray local file or miss a tracked one. It refuses outright
# if the tree is dirty, because an archive that does not match the commit it claims to be is
# worse than none.
echo "==> source archive"
if [ -n "$(git status --porcelain)" ]; then
  echo
  echo "REFUSING to build the source archive: the working tree has uncommitted changes." >&2
  echo "The archive must match the commit it claims to be, or a reviewer cannot reproduce" >&2
  echo "the build from it. Commit or stash, then re-run." >&2
  git status --short >&2
  exit 1
fi
git archive --format=zip --prefix='' -o "dist-store/corpus-retriever-$VERSION-SOURCE.zip" HEAD

echo
echo "Done. Upload these:"
ls -1 "dist-store/corpus-retriever-$VERSION$SUFFIX.zip" \
      "dist-store/corpus-retriever-$VERSION-firefox$SUFFIX.xpi" \
      "dist-store/corpus-retriever-$VERSION-SOURCE.zip"
